services:
  postgres:
    image: postgres:16-alpine
    container_name: FlagForge
    restart: always
    environment:
      POSTGRES_USER: FlagForgeUser
      POSTGRES_PASSWORD: FlagForgePassword
      POSTGRES_DB: FlagForgeDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
